baseURL = 'https://blog.gitbundle.com'
title = 'Cloud Native Git Service'
author = 'cgxxv'
copyright = "GitBundle"
paginate = 10
languageCode = 'en-us'
theme = "tailwind"


[params]
  keywords = "GitBundle, Cloud Native Git Service, CI/CD, 云原生 Git 服务"
  subtitle = "Cloud Native Git Service (云原生 Git 服务)"

  showMenu = false
  showTaxonomies = false

  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  [params.header]
    logo = "logo.png"


  [params.footer]
    since = 2023
    poweredby = false

[menu]

  [[menu.main]]
    identifier = "post"
    name = "Post"
    pageRef = "/posts"
    weight = 0

  [[menu.main]]
    identifier = "about"
    name = "About"
    pageRef = "/about"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"